[build]
  publish = "."

# Subdomain routing - serve correct content based on domain
[[redirects]]
  from = "https://aireceptionist.perfectaimarketing.com/*"
  to = "/aireceptionist/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://247receptionist.perfectaimarketing.com/*"
  to = "/aireceptionist/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://medcor.perfectaimarketing.com/*"
  to = "/medcor-landing/:splat"
  status = 200
  force = true

# Ensure index files are served for directory roots
[[redirects]]
  from = "/aireceptionist"
  to = "/aireceptionist/index.html"
  status = 200

[[redirects]]
  from = "/medcor-landing"
  to = "/medcor-landing/index.html"
  status = 200

# Legal pages for AIReceptionist subdomain
[[redirects]]
  from = "https://aireceptionist.perfectaimarketing.com/privacy-policy"
  to = "/aireceptionist/privacy-policy.html"
  status = 200
  force = true

[[redirects]]
  from = "https://aireceptionist.perfectaimarketing.com/terms-and-conditions"
  to = "/aireceptionist/terms-and-conditions.html"
  status = 200
  force = true

[[redirects]]
  from = "https://aireceptionist.perfectaimarketing.com/legal/AI_Generated_Evidence_in_Criminal_Defense.pdf"
  to = "/aireceptionist/legal/AI_Generated_Evidence_in_Criminal_Defense.pdf"
  status = 200
  force = true

[[redirects]]
  from = "https://247receptionist.perfectaimarketing.com/privacy-policy"
  to = "/aireceptionist/privacy-policy.html"
  status = 200
  force = true

[[redirects]]
  from = "https://247receptionist.perfectaimarketing.com/terms-and-conditions"
  to = "/aireceptionist/terms-and-conditions.html"
  status = 200
  force = true

# Legal pages for MedCor subdomain
[[redirects]]
  from = "https://medcor.perfectaimarketing.com/privacy-policy"
  to = "/medcor-landing/privacy-policy.html"
  status = 200
  force = true

[[redirects]]
  from = "https://medcor.perfectaimarketing.com/terms-and-conditions"
  to = "/medcor-landing/terms-and-conditions.html"
  status = 200
  force = true

# Form handling configuration
[forms]
  honeypot = "_gotcha"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache control for static assets
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "/*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "/*.gif"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "/*.avif"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "/*.pdf"
  [headers.values]
    Cache-Control = "public, max-age=2592000"
    Content-Type = "application/pdf"
